'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class bukutambah

    '''<summary>
    '''judul_buku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents judul_buku As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''stok control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stok As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tgl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tgl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''kategori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kategori As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''nama_pengarang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nama_pengarang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gambar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gambar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sinopsis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sinopsis As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''tambahbuku control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tambahbuku As Global.System.Web.UI.WebControls.LinkButton
End Class
